version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # TODO: npm - ensure that I keep bedrock pinned until they fix the issue
      #       https://github.com/aws/aws-sdk-js-v3/issues/6269
      - dependency-name: "@aws-sdk/client-bedrock-runtime"
