---
name: CI
on:
  push:
    branches:
      - main
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - run: npm audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - run: npm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - run: npm run format

  build:
    runs-on: ubuntu-latest
    needs: [security, lint, format]
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: eas build --non-interactive --platform ios

  dependabot:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    needs: [build]
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
