---
name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - run: npm audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - run: npm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - run: npm ci
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - run: npm run format
